version: "3"

services:
  slides:
    build: .
  portal:
    image: steveltn/https-portal:1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - slides
    environment:
      DOMAINS: "covid19.minsky.cc -> http://slides:80"
      STAGE: "production"
      # FORCE_RENEW: 'true'
